version: "3.3"

services:

    db:
        container_name: postgresql_db
        image: postgres
        restart: always
        ports:
            - 5432:5432
        environment: :
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_NAME=${DB_NAME}