"""New Migration

Revision ID: 17f783884667
Revises: bb7cd1d3b6ea
Create Date: 2021-06-30 10:29:44.967283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17f783884667'
down_revision = 'bb7cd1d3b6ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
