"""New Migration

Revision ID: 256cb64419d2
Revises: 17f783884667
Create Date: 2021-06-30 10:30:19.518358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '256cb64419d2'
down_revision = '17f783884667'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
