"""New Migration

Revision ID: 2a83f266d9e2
Revises: d524f431b7d6
Create Date: 2021-06-30 10:37:42.946483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a83f266d9e2'
down_revision = 'd524f431b7d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
