"""New Migration

Revision ID: 64b0b5706e15
Revises: 7ccf5a099d28
Create Date: 2021-06-30 10:44:06.080852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64b0b5706e15'
down_revision = '7ccf5a099d28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
