"""New Migration

Revision ID: 6d44975e8ed5
Revises: fcadb8cf1f9e
Create Date: 2021-06-30 10:35:37.166614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d44975e8ed5'
down_revision = 'fcadb8cf1f9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
