"""New Migration

Revision ID: 77973ebfad27
Revises: d29a03d5e2c5
Create Date: 2021-06-30 10:40:50.805574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77973ebfad27'
down_revision = 'd29a03d5e2c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
