"""New Migration

Revision ID: 786af2a33bec
Revises: c51523db06d5
Create Date: 2021-06-30 10:33:01.900754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '786af2a33bec'
down_revision = 'c51523db06d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
