"""New Migration

Revision ID: 7ccf5a099d28
Revises: a66915d79548
Create Date: 2021-06-30 10:42:58.753584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ccf5a099d28'
down_revision = 'a66915d79548'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
