"""New Migration

Revision ID: 83af64bfce10
Revises: c5632805d5d6
Create Date: 2021-06-30 10:31:23.512047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83af64bfce10'
down_revision = 'c5632805d5d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
