"""New Migration

Revision ID: 88d719d4d63a
Revises: f3bb2c02817f
Create Date: 2021-06-30 10:46:16.244235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88d719d4d63a'
down_revision = 'f3bb2c02817f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
