"""New Migration

Revision ID: a66915d79548
Revises: 77973ebfad27
Create Date: 2021-06-30 10:41:53.788703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a66915d79548'
down_revision = '77973ebfad27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
