"""New Migration

Revision ID: acf531067c45
Revises: c4bd7f3106a6
Create Date: 2021-06-30 10:50:47.706951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acf531067c45'
down_revision = 'c4bd7f3106a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
