"""New Migration

Revision ID: c4bd7f3106a6
Revises: fd95167a2a24
Create Date: 2021-06-30 10:48:28.983897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4bd7f3106a6'
down_revision = 'fd95167a2a24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
