"""New Migration

Revision ID: c51523db06d5
Revises: 83af64bfce10
Create Date: 2021-06-30 10:31:54.456761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c51523db06d5'
down_revision = '83af64bfce10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
