"""New Migration

Revision ID: c5632805d5d6
Revises: 256cb64419d2
Create Date: 2021-06-30 10:30:51.110268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5632805d5d6'
down_revision = '256cb64419d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
