"""New Migration

Revision ID: d29a03d5e2c5
Revises: ec204d17f240
Create Date: 2021-06-30 10:39:47.953744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd29a03d5e2c5'
down_revision = 'ec204d17f240'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
