"""New Migration

Revision ID: d524f431b7d6
Revises: 6d44975e8ed5
Create Date: 2021-06-30 10:36:39.858793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd524f431b7d6'
down_revision = '6d44975e8ed5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
