"""New Migration

Revision ID: ec204d17f240
Revises: 2a83f266d9e2
Create Date: 2021-06-30 10:38:45.569019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec204d17f240'
down_revision = '2a83f266d9e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
