"""New Migration

Revision ID: f3bb2c02817f
Revises: 64b0b5706e15
Create Date: 2021-06-30 10:45:10.621386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3bb2c02817f'
down_revision = '64b0b5706e15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
