"""New Migration

Revision ID: f9fb8720f2dd
Revises: c4bd7f3106a6
Create Date: 2021-06-30 10:50:47.433789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9fb8720f2dd'
down_revision = 'c4bd7f3106a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
