"""New Migration

Revision ID: fcadb8cf1f9e
Revises: 786af2a33bec
Create Date: 2021-06-30 10:34:09.462974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcadb8cf1f9e'
down_revision = '786af2a33bec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
