"""New Migration

Revision ID: fd95167a2a24
Revises: 88d719d4d63a
Create Date: 2021-06-30 10:47:24.198332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd95167a2a24'
down_revision = '88d719d4d63a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
